[package]
name = "rsaref-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md-5 = "0.10.1"
rsa = "0.6.1"
num-integer = "0.1.45"
rand = "0.8.5"